import React from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import Navbar from "../components/Navbar/index"
import Gallery from "../components/Gallery/index"

export default function Home() {

  const [src, setSrc] = React.useState();
  const [error, setError] = React.useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          defer
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin="anonymous"
        />
      </Head>

      <Navbar setSrc={setSrc} setError={setError} />
      <Gallery src={src} err={error} />

    </div>
  )
}
